// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfykvhtnzxwcaearrirn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmeWt2aHRuenh3Y2FlYXJyaXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MzIwODEsImV4cCI6MjA2NzUwODA4MX0.7wGXEj8LKGLBiCEuNqy6FddnYa8ECsyBnlMCrkSse-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});